import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../models/agent_mode.dart';

/// Generates a PDF from an [ExportDocument] and shares it.
class ExportService {
  ExportService._();

  static Future<File> generatePdf(ExportDocument doc) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              doc.title,
              style: pw.TextStyle(
                fontSize: 24,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            'Generated by Arqivon',
            style: const pw.TextStyle(
              fontSize: 10,
              color: PdfColors.grey600,
            ),
          ),
          pw.SizedBox(height: 20),
          // Main content
          if (doc.sections.isEmpty)
            pw.Paragraph(
              text: doc.content,
              style: const pw.TextStyle(fontSize: 12, lineSpacing: 5),
            )
          else
            ...doc.sections.map((section) {
              final heading = section['heading'] as String? ?? '';
              final body = section['body'] as String? ?? '';
              return pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  if (heading.isNotEmpty)
                    pw.Header(
                      level: 1,
                      child: pw.Text(
                        heading,
                        style: pw.TextStyle(
                          fontSize: 16,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                    ),
                  pw.Paragraph(
                    text: body,
                    style: const pw.TextStyle(fontSize: 12, lineSpacing: 5),
                  ),
                  pw.SizedBox(height: 10),
                ],
              );
            }),
        ],
      ),
    );

    final dir = await getTemporaryDirectory();
    final sanitized = doc.title.replaceAll(RegExp(r'[^\w\s-]'), '').trim();
    final file = File('${dir.path}/$sanitized.pdf');
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  static Future<void> sharePdf(ExportDocument doc) async {
    final file = await generatePdf(doc);
    await Share.shareXFiles(
      [XFile(file.path)],
      subject: doc.title,
    );
  }
}
