import 'dart:io';

import 'package:flutter/services.dart' show rootBundle;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../models/agent_mode.dart';

/// Generates a PDF from an [ExportDocument] and shares it.
class ExportService {
  ExportService._();

  /// Cached Unicode-capable font for PDF rendering.
  static pw.Font? _unicodeFont;
  static pw.Font? _unicodeBoldFont;

  /// Try to load a bundled Noto Sans font for broad Unicode coverage.
  /// Falls back to Helvetica if the asset isn't available.
  static Future<pw.ThemeData> _pdfTheme() async {
    // Try to load NotoSans from assets for CJK / Arabic / Cyrillic support.
    // If the asset isn't bundled, fall back gracefully to Helvetica.
    if (_unicodeFont == null) {
      try {
        final regular = await rootBundle.load(
          'assets/fonts/NotoSans-Regular.ttf',
        );
        _unicodeFont = pw.Font.ttf(regular);
        final bold = await rootBundle.load(
          'assets/fonts/NotoSans-Bold.ttf',
        );
        _unicodeBoldFont = pw.Font.ttf(bold);
      } catch (_) {
        // Font not bundled — use default Helvetica (Latin-only).
      }
    }

    if (_unicodeFont != null) {
      return pw.ThemeData.withFont(
        base: _unicodeFont!,
        bold: _unicodeBoldFont ?? _unicodeFont!,
      );
    }
    return pw.ThemeData.base();
  }

  static Future<File> generatePdf(ExportDocument doc) async {
    final pdf = pw.Document();
    final theme = await _pdfTheme();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        theme: theme,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              doc.title,
              style: pw.TextStyle(
                fontSize: 24,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            'Generated by Arqivon',
            style: const pw.TextStyle(
              fontSize: 10,
              color: PdfColors.grey600,
            ),
          ),
          pw.SizedBox(height: 20),
          // Main content
          if (doc.sections.isEmpty)
            pw.Paragraph(
              text: doc.content,
              style: const pw.TextStyle(fontSize: 12, lineSpacing: 5),
            )
          else
            ...doc.sections.map((section) {
              final heading = section['heading'] as String? ?? '';
              final body = section['body'] as String? ?? '';
              return pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  if (heading.isNotEmpty)
                    pw.Header(
                      level: 1,
                      child: pw.Text(
                        heading,
                        style: pw.TextStyle(
                          fontSize: 16,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                    ),
                  pw.Paragraph(
                    text: body,
                    style: const pw.TextStyle(fontSize: 12, lineSpacing: 5),
                  ),
                  pw.SizedBox(height: 10),
                ],
              );
            }),
        ],
      ),
    );

    final dir = await getTemporaryDirectory();
    var sanitized = doc.title.replaceAll(RegExp(r'[^\w\s-]'), '').trim();
    if (sanitized.isEmpty) sanitized = 'arqivon_export';
    final file = File('${dir.path}/$sanitized.pdf');
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  static Future<void> sharePdf(ExportDocument doc) async {
    final file = await generatePdf(doc);
    await Share.shareXFiles(
      [XFile(file.path)],
      subject: doc.title,
    );
  }
}
